/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ControleDeEstoque.view;

import br.com.ControleDeEstoque.dao.ProductsDAO;
import br.com.ControleDeEstoque.model.Products;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author livia
 */
public class FrmInventory extends javax.swing.JFrame {
    int idproduto, qtd_nova;
    
    // Método Listar na tabela 
    public void listarTabela() {
        ProductsDAO dao = new ProductsDAO();
        List<Products> lista = dao.listarProdutos();
        DefaultTableModel dados = (DefaultTableModel) tabelaproduto.getModel();
        dados.setNumRows(0);

        for (Products c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getDescricao(),
                c.getPreco(),
                c.getQtd_estoque(),
                c.getFornecedor().getNome(),
                
            });
        }
}
// Fim do método listarTabela

    /**
     * Creates new form FrmInventory
     */
    public FrmInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtnome4 = new javax.swing.JLabel();
        jdatainicio1 = new javax.swing.JFormattedTextField();
        txtnome5 = new javax.swing.JLabel();
        jdatafim2 = new javax.swing.JFormattedTextField();
        btnbusca2 = new javax.swing.JButton();
        txtnome6 = new javax.swing.JLabel();
        jdatafim3 = new javax.swing.JFormattedTextField();
        btnbusca3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaproduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtnome7 = new javax.swing.JLabel();
        txtnome8 = new javax.swing.JLabel();
        btnbusca4 = new javax.swing.JButton();
        txtnome9 = new javax.swing.JLabel();
        btnbusca5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpesquisa = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jestoque = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jqtdnova = new javax.swing.JTextPane();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta por data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)), "Consulta de Produtos")); // NOI18N

        txtnome4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnome4.setText("Descrição:");

        try {
            jdatainicio1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jdatainicio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jdatainicio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdatainicio1KeyPressed(evt);
            }
        });

        txtnome5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnome5.setText("Estoque atual:");

        try {
            jdatafim2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jdatafim2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jdatafim2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdatafim2KeyPressed(evt);
            }
        });

        btnbusca2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbusca2.setText("Pesquisar");
        btnbusca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusca2ActionPerformed(evt);
            }
        });
        btnbusca2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbusca2KeyPressed(evt);
            }
        });

        txtnome6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnome6.setText("Qtde:");

        try {
            jdatafim3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jdatafim3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jdatafim3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdatafim3KeyPressed(evt);
            }
        });

        btnbusca3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbusca3.setText("Adicionar");
        btnbusca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusca3ActionPerformed(evt);
            }
        });
        btnbusca3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbusca3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtnome4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdatainicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtnome5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdatafim2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnome6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdatafim3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbusca2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbusca3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome4)
                    .addComponent(jdatainicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbusca2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdatafim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdatafim3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome6)
                    .addComponent(btnbusca3)
                    .addComponent(txtnome5))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tabelaproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço", "Qtde. Estoque", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaprodutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaproduto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 51, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle de Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtnome7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnome7.setText("Descrição:");

        txtnome8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnome8.setText("Estoque atual:");

        btnbusca4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbusca4.setText("Pesquisar");
        btnbusca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusca4ActionPerformed(evt);
            }
        });
        btnbusca4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbusca4KeyPressed(evt);
            }
        });

        txtnome9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnome9.setText("Qtde:");

        btnbusca5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbusca5.setText("Adicionar");
        btnbusca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusca5ActionPerformed(evt);
            }
        });
        btnbusca5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbusca5KeyPressed(evt);
            }
        });

        jpesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jpesquisa);

        jestoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(jestoque);

        jqtdnova.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(jqtdnova);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtnome7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtnome8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtnome9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbusca5, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(btnbusca4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnome7)
                        .addComponent(btnbusca4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome9)
                            .addComponent(btnbusca5)
                            .addComponent(txtnome8))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaprodutoMouseClicked
        idproduto = Integer.parseInt(tabelaproduto.getValueAt(tabelaproduto.getSelectedRow(), 0).toString());
        jpesquisa.setText(tabelaproduto.getValueAt(tabelaproduto.getSelectedRow(), 1).toString());
        jestoque.setText(tabelaproduto.getValueAt(tabelaproduto.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tabelaprodutoMouseClicked

    private void jdatainicio1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdatainicio1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdatainicio1KeyPressed

    private void jdatafim2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdatafim2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdatafim2KeyPressed

    private void btnbusca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbusca2ActionPerformed

    private void btnbusca2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbusca2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbusca2KeyPressed

    private void jdatafim3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdatafim3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdatafim3KeyPressed

    private void btnbusca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusca3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbusca3ActionPerformed

    private void btnbusca3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbusca3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbusca3KeyPressed

    private void btnbusca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusca4ActionPerformed
            // Botão pesquisar
        String nome = "%" + jpesquisa.getText() + "%";

        ProductsDAO dao = new ProductsDAO();
        List<Products> lista = dao.listarProdutosPorNome(nome);

        DefaultTableModel dados = (DefaultTableModel) tabelaproduto.getModel();
        dados.setNumRows(0);

        for (Products c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getDescricao(),
                c.getPreco(),
                c.getQtd_estoque(),
                c.getFornecedor().getNome(),
            });
        }
    }//GEN-LAST:event_btnbusca4ActionPerformed

    private void btnbusca4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbusca4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbusca4KeyPressed

    private void btnbusca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusca5ActionPerformed
        try {
            int qtd_estoque, qtd_atualizada;
            qtd_estoque =  Integer.parseInt(jestoque.getText());
            qtd_atualizada = Integer.parseInt(jqtdnova.getText());
            
            qtd_nova = qtd_estoque + qtd_atualizada;
            ProductsDAO dao = new ProductsDAO();
            
            dao.adicionarEstoque(idproduto, qtd_nova);
            
            JOptionPane.showMessageDialog(null, "Estoque do produto atualizado");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado no estoque");
        }
    }//GEN-LAST:event_btnbusca5ActionPerformed

    private void btnbusca5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbusca5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbusca5KeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      listarTabela();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventory().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbusca2;
    private javax.swing.JButton btnbusca3;
    private javax.swing.JButton btnbusca4;
    private javax.swing.JButton btnbusca5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JFormattedTextField jdatafim2;
    private javax.swing.JFormattedTextField jdatafim3;
    private javax.swing.JFormattedTextField jdatainicio1;
    private javax.swing.JTextPane jestoque;
    private javax.swing.JTextPane jpesquisa;
    private javax.swing.JTextPane jqtdnova;
    private javax.swing.JTable tabelaproduto;
    private javax.swing.JLabel txtnome4;
    private javax.swing.JLabel txtnome5;
    private javax.swing.JLabel txtnome6;
    private javax.swing.JLabel txtnome7;
    private javax.swing.JLabel txtnome8;
    private javax.swing.JLabel txtnome9;
    // End of variables declaration//GEN-END:variables

}