/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ControleDeEstoque.view;

import br.com.ControleDeEstoque.dao.SalesDAO;
import br.com.ControleDeEstoque.model.Clientes;
import br.com.ControleDeEstoque.model.Sales;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author livia
 */
public class FrmPayments extends javax.swing.JFrame {
    Clientes cliente = new Clientes();

    /**
     * Creates new form FrmPayments
     */
    public FrmPayments() {
        initComponents();
        jcartao.setText("0");
        jdinheiro.setText("0");
        jcheque.setText("0");
        jtroco.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnome4 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnome5 = new javax.swing.JLabel();
        jdinheiro = new javax.swing.JTextField();
        txtnome6 = new javax.swing.JLabel();
        jcartao = new javax.swing.JTextField();
        txtnome7 = new javax.swing.JLabel();
        jcheque = new javax.swing.JTextField();
        txtnome8 = new javax.swing.JLabel();
        jtroco = new javax.swing.JTextField();
        txtnome9 = new javax.swing.JLabel();
        jtotal = new javax.swing.JTextField();
        jfinalizar = new javax.swing.JButton();
        txtnome10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOBS = new javax.swing.JTextArea();

        txtnome4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnome4.setText("Código:");

        jcodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Pagamentos");

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pagamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        txtnome5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnome5.setText("OBS:");

        jdinheiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtnome6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnome6.setText("CARTÃO:");

        jcartao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtnome7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnome7.setText("CHEQUE:");

        jcheque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtnome8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnome8.setText("TROCO:");

        jtroco.setEditable(false);
        jtroco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtnome9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnome9.setText("TOTAL:");

        jtotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jfinalizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfinalizar.setText("Finalizar Venda");
        jfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfinalizarActionPerformed(evt);
            }
        });

        txtnome10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnome10.setText("DINHEIRO:");

        jOBS.setColumns(20);
        jOBS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jOBS.setRows(5);
        jScrollPane1.setViewportView(jOBS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnome6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcartao)
                                .addGap(1, 1, 1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnome8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtnome9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(txtnome7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcheque, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfinalizar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnome10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addComponent(txtnome5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnome6)
                                    .addComponent(jcartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtnome5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome7)
                            .addComponent(jcheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome8)
                    .addComponent(jtroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome9)
                    .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jfinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfinalizarActionPerformed
        
        double pcartao, pcheque, pdinheiro, totalpago, totalvenda, troco;
        pcartao = Double.parseDouble(jcartao.getText());
        pcheque = Double.parseDouble(jcheque.getText());
        pdinheiro = Double.parseDouble(jdinheiro.getText());
        
        totalvenda = Double.parseDouble(jtotal.getText());
        
        //Calculando o troco
        totalpago = pcartao+pcheque+pdinheiro;
        troco = totalpago - totalvenda;
        
        jtroco.setText(String.valueOf(troco));
        
        Sales objv = new Sales();
        objv.setCliente(cliente);
        
        Date agora = new Date();
        SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy-MM-dd");
        String datamysql = dataEUA.format(agora);
        
        //total da venda e obs
        objv.setData_venda(datamysql);
        
        objv.setTotal_venda(totalvenda);
        
        objv.setObs(jOBS.getText());
        
        SalesDAO dao_v = new SalesDAO();
        dao_v.cadastrarVenda(objv);
        
        //retorna o id da ultima venda realizada
        objv.setId(dao_v.retornaUltimaVenda());
        
        System.out.println("Id da última venda: " + objv.getId());
    }//GEN-LAST:event_jfinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPayments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jOBS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcartao;
    private javax.swing.JTextField jcheque;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JTextField jdinheiro;
    private javax.swing.JButton jfinalizar;
    public javax.swing.JTextField jtotal;
    private javax.swing.JTextField jtroco;
    private javax.swing.JLabel txtnome10;
    private javax.swing.JLabel txtnome4;
    private javax.swing.JLabel txtnome5;
    private javax.swing.JLabel txtnome6;
    private javax.swing.JLabel txtnome7;
    private javax.swing.JLabel txtnome8;
    private javax.swing.JLabel txtnome9;
    // End of variables declaration//GEN-END:variables
}
